name: CMake

on:
  push:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ip_filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install -y clang++-12
      - run: pip install conan
      - run: conan profile new default --detect
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install --build missing -if ${{github.workspace}}/build .
      - run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=/bin/clang++-12 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPATCH_VERSION=${{ github.run_number }}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ip_filter
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target test_ip_filter
      - run: ${{github.workspace}}/build/bin/test_ip_filter
      - run: python ip_filter/integration/hash_test.py
      - run: cmake --build ${{github.workspace}}/build --target package
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: ip_filter ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: github.ref == 'refs/heads/master'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{github.workspace}}/build/_CPack_Packages/Linux/DEB/ip_filter-0.0.${{ github.run_number }}-Linux.deb
          asset_name: ip_filter-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

  print_ip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install -y clang++-12
      - run: pip install conan
      - run: conan profile new default --detect
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install --build missing -if ${{github.workspace}}/build .
      - run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=/bin/clang++-12 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPATCH_VERSION=${{ github.run_number }}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target print_ip
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target test_print_ip
      - run: ${{github.workspace}}/build/bin/test_print_ip
      - run: cmake --build ${{github.workspace}}/build --target package print_ip
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: print_ip ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: github.ref == 'refs/heads/master'
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{github.workspace}}/build/_CPack_Packages/Linux/DEB/print_ip-0.0.${{ github.run_number }}-Linux.deb
          asset_name: print_ip-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package